brew "ack"
brew "autoconf"
brew "readline"
brew "openssl@3"
brew "bat"
brew "cmake"
brew "direnv"
brew "dive"
brew "dust"
brew "eza"
brew "fd"
brew "fish"
brew "fzf"
brew "git-delta"
brew "glow"
brew "gmp"
brew "gnupg"
brew "hledger"
brew "htop"
brew "httpie"
brew "jnv"
brew "jq"
brew "just"
brew "k9s"
brew "lazygit"
brew "libpq"
brew "libyaml"
brew "mas"
brew "mise"
brew "ripgrep"
brew "rust"
brew "starship"
brew "tealdeer"
brew "tmux"
brew "tree-sitter"
brew "tree-sitter-cli"
brew "trivy"
brew "yq"
cask "amethyst"
cask "arc"
cask "bruno"
cask "chatgpt"
cask "font-jetbrains-mono-nerd-font"
cask "jordanbaird-ice"
cask "logseq"
cask "obsidian"
cask "orbstack"
mas "1Password for Safari", id: 1569813296
mas "Color Picker", id: 1545870783
mas "Flow", id: 1423210932
mas "Keynote", id: 409183694
mas "LanguageTool", id: 1534275760
mas "Little Snitch Mini", id: 1629008763
mas "Noir", id: 1592917505
mas "Numbers", id: 409203825
mas "OpenIn", id: 1643649331
mas "Owly", id: 882812218
mas "Pages", id: 409201541
mas "Proton Pass for Safari", id: 6502835663
mas "Surfingkeys", id: 1609752330
mas "Tailscale", id: 1475387142
mas "Telegram", id: 747648890
mas "Wipr", id: 1662217862
mas "Yubico Authenticator", id: 1497506650
