tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-fonts"
tap "romkatv/gitstatus"

brew "openssh"
brew "zsh"
brew "tmux"
brew "docker"
brew "docker-compose"
brew "htop"
brew "git"
brew "midnight-commander"
brew "broot"
brew "cask"
brew "nvm"
brew "ack"
brew "jq"
brew "fzf"
brew "git-flow-avh"
brew "colordiff"
brew "tealdeer"
brew "git-delta"
brew "lazygit"
brew "bat"
brew "lsd"
brew "neovim"
brew "fd"
brew "bottom"
brew "antidote"
brew "romkatv/gitstatus/gitstatus"

cask "browserosaurus"
cask "font-jetbrains-mono-nerd-font"

brew "bitwarden-cli"
