#!/usr/bin/env bash

# PLUGIN_DIR used in items
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined colors

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants

# Setting up the general bar appearance and default values
bar=(
  height=24
  color=0x00000000
  position=top
  y_offset=12
)

sketchybar --bar "${bar[@]}"

default=(
  updates=when_shown
  label.font="$FONT:Semibold:13.0"
  icon.font="$FONT:Bold:14.0" 

  icon.color="$ICON_COLOR"
  label.color="$LABEL_COLOR"

  icon.padding_left=8
  icon.padding_right=4

  label.padding_left=4
  label.padding_right=8 

  background.padding_right=4
  background.padding_left=4

  background.color="$BAR_COLOR"
  background.corner_radius=5
)

sketchybar --default "${default[@]}"

sketchybar --add event window_focus --add event title_change

# Left side
source "$ITEM_DIR/spaces.sh"

# Center
source "$ITEM_DIR/front_app.sh"

# Right side
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/keyboard.sh"


##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update

echo "sketchybar configuation loaded.."
