#! /bin/zsh
export skip_global_compinit=1

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# NOTE: Add same configs for all shells
[ -f "$HOME/.config/shell/shell.sh" ] && . "$HOME/.config/shell/shell.sh"

add_all "$HOME"/.config/zsh/extensions/*.zsh
add_file ~/.fzf.zsh

# NOTE: vim mode
bindkey -v

setopt auto_cd

add_file "$HOME/.config/zsh/zshrc-after" 

# Open in tmux popup if on tmux, otherwise use --height mode
export FZF_DEFAULT_OPTS='--height 40% --tmux bottom,40% --layout reverse --border top'
